import 'dart:convert';

class ViewVentasModel {
  int documento;
  int tipoDocumento;
  String serieDocumento;
  int empresa;
  int localizacion;
  int estacionTrabajo;
  int fechaReg;
  int estadoDocumento;
  String desTipoDocumento;
  String desSerieDocumento;
  DateTime fechaHora;
  String userName;
  String idDocumento;
  dynamic refIdDocumento;
  dynamic refSerie;
  String documentoNombre;
  String documentoNit;
  dynamic fECae;
  dynamic fENumeroDocumento;
  dynamic fENumeroDte;
  dynamic feLUuidAnulacion;
  DateTime fechaDocumento;
  int? cuentaCorrentista;
  int? cuentaCorrentistaRef;
  int? nacionalidad;
  String? idCuenta;
  String? nombre;
  dynamic idVendedor;
  dynamic vendedor;
  int producto;
  int unidadMedida;
  int bodega;
  int claseProducto;
  int marca;
  String productoId;
  String desProducto;
  String desUnidadMedida;
  dynamic desMarca;
  String desBodega;
  String desClaseProducto;
  bool exento;
  int estado;
  bool reversion;
  double cantidadAnt;
  double cantidad;
  double cantidadPos;
  double monto;
  double montoSinIva;
  double iva;
  double costoTotal;
  double existencia;
  double costoInventario;
  dynamic cantFacturada;

  ViewVentasModel({
    required this.documento,
    required this.tipoDocumento,
    required this.serieDocumento,
    required this.empresa,
    required this.localizacion,
    required this.estacionTrabajo,
    required this.fechaReg,
    required this.estadoDocumento,
    required this.desTipoDocumento,
    required this.desSerieDocumento,
    required this.fechaHora,
    required this.userName,
    required this.idDocumento,
    required this.refIdDocumento,
    required this.refSerie,
    required this.documentoNombre,
    required this.documentoNit,
    required this.fECae,
    required this.fENumeroDocumento,
    required this.fENumeroDte,
    required this.feLUuidAnulacion,
    required this.fechaDocumento,
    required this.cuentaCorrentista,
    required this.cuentaCorrentistaRef,
    required this.nacionalidad,
    required this.idCuenta,
    required this.nombre,
    required this.idVendedor,
    required this.vendedor,
    required this.producto,
    required this.unidadMedida,
    required this.bodega,
    required this.claseProducto,
    required this.marca,
    required this.productoId,
    required this.desProducto,
    required this.desUnidadMedida,
    required this.desMarca,
    required this.desBodega,
    required this.desClaseProducto,
    required this.exento,
    required this.estado,
    required this.reversion,
    required this.cantidadAnt,
    required this.cantidad,
    required this.cantidadPos,
    required this.monto,
    required this.montoSinIva,
    required this.iva,
    required this.costoTotal,
    required this.existencia,
    required this.costoInventario,
    required this.cantFacturada,
  });

  factory ViewVentasModel.fromJson(String str) =>
      ViewVentasModel.fromMap(json.decode(str));

  String toJson() => json.encode(toMap());

  factory ViewVentasModel.fromMap(Map<String, dynamic> json) => ViewVentasModel(
        documento: json["documento"],
        tipoDocumento: json["tipo_Documento"],
        serieDocumento: json["serie_Documento"],
        empresa: json["empresa"],
        localizacion: json["localizacion"],
        estacionTrabajo: json["estacion_Trabajo"],
        fechaReg: json["fecha_Reg"],
        estadoDocumento: json["estado_Documento"],
        desTipoDocumento: json["des_Tipo_Documento"],
        desSerieDocumento: json["des_Serie_Documento"],
        fechaHora: DateTime.parse(json["fecha_Hora"]),
        userName: json["userName"],
        idDocumento: json["id_Documento"],
        refIdDocumento: json["ref_Id_Documento"],
        refSerie: json["ref_Serie"],
        documentoNombre: json["documento_Nombre"],
        documentoNit: json["documento_NIT"],
        fECae: json["fE_CAE"],
        fENumeroDocumento: json["fE_numeroDocumento"],
        fENumeroDte: json["fE_numeroDte"],
        feLUuidAnulacion: json["feL_UUID_Anulacion"],
        fechaDocumento: DateTime.parse(json["fecha_Documento"]),
        cuentaCorrentista: json["cuenta_Correntista"],
        cuentaCorrentistaRef: json["cuenta_Correntista_Ref"],
        nacionalidad: json["nacionalidad"],
        idCuenta: json["id_Cuenta"],
        nombre: json["nombre"],
        idVendedor: json["id_Vendedor"],
        vendedor: json["vendedor"],
        producto: json["producto"],
        unidadMedida: json["unidad_Medida"],
        bodega: json["bodega"],
        claseProducto: json["clase_Producto"],
        marca: json["marca"],
        productoId: json["producto_Id"],
        desProducto: json["des_Producto"],
        desUnidadMedida: json["des_Unidad_Medida"],
        desMarca: json["des_Marca"],
        desBodega: json["des_Bodega"],
        desClaseProducto: json["des_Clase_Producto"],
        exento: json["exento"],
        estado: json["estado"],
        reversion: json["reversion"],
        cantidadAnt: json["cantidad_Ant"],
        cantidad: json["cantidad"],
        cantidadPos: json["cantidad_Pos"],
        monto: json["monto"],
        montoSinIva: json["monto_SinIVA"]?.toDouble(),
        iva: json["iva"]?.toDouble(),
        costoTotal: json["costo_Total"],
        existencia: json["existencia"],
        costoInventario: json["costo_inventario"],
        cantFacturada: json["cant_Facturada"],
      );

  Map<String, dynamic> toMap() => {
        "documento": documento,
        "tipo_Documento": tipoDocumento,
        "serie_Documento": serieDocumento,
        "empresa": empresa,
        "localizacion": localizacion,
        "estacion_Trabajo": estacionTrabajo,
        "fecha_Reg": fechaReg,
        "estado_Documento": estadoDocumento,
        "des_Tipo_Documento": desTipoDocumento,
        "des_Serie_Documento": desSerieDocumento,
        "fecha_Hora": fechaHora.toIso8601String(),
        "userName": userName,
        "id_Documento": idDocumento,
        "ref_Id_Documento": refIdDocumento,
        "ref_Serie": refSerie,
        "documento_Nombre": documentoNombre,
        "documento_NIT": documentoNit,
        "fE_CAE": fECae,
        "fE_numeroDocumento": fENumeroDocumento,
        "fE_numeroDte": fENumeroDte,
        "feL_UUID_Anulacion": feLUuidAnulacion,
        "fecha_Documento": fechaDocumento.toIso8601String(),
        "cuenta_Correntista": cuentaCorrentista,
        "cuenta_Correntista_Ref": cuentaCorrentistaRef,
        "nacionalidad": nacionalidad,
        "id_Cuenta": idCuenta,
        "nombre": nombre,
        "id_Vendedor": idVendedor,
        "vendedor": vendedor,
        "producto": producto,
        "unidad_Medida": unidadMedida,
        "bodega": bodega,
        "clase_Producto": claseProducto,
        "marca": marca,
        "producto_Id": productoId,
        "des_Producto": desProducto,
        "des_Unidad_Medida": desUnidadMedida,
        "des_Marca": desMarca,
        "des_Bodega": desBodega,
        "des_Clase_Producto": desClaseProducto,
        "exento": exento,
        "estado": estado,
        "reversion": reversion,
        "cantidad_Ant": cantidadAnt,
        "cantidad": cantidad,
        "cantidad_Pos": cantidadPos,
        "monto": monto,
        "monto_SinIVA": montoSinIva,
        "iva": iva,
        "costo_Total": costoTotal,
        "existencia": existencia,
        "costo_inventario": costoInventario,
        "cant_Facturada": cantFacturada,
      };
}
