import 'dart:convert';

class PrintConvertModel {
  String? montoLetras;
  String? idDocumento;
  dynamic refIdDocumento;
  String? username;
  String? razonSocial;
  String? empresaNombre;
  String? empresaDireccion;
  String? empresaNit;
  String? paginaWeb;
  String? empresaCorreo;
  String? empresaPbx;
  String? empresaDireccionF;
  String? empresaTelefono;
  String? tipoDocumento;
  String? serieDocumento;
  String? serieResolucion;
  String? serieFechaAutorizacion;
  String? serieIni;
  String? serieFin;
  String? serieFormaPago;
  String? sucursalTelefono;
  String? sucursalDireccion;
  String? sucursalNombre;
  String? departamentoSerie;
  String? municipioSerie;
  dynamic fEIdDocumento;
  dynamic fESerie;
  dynamic fECae;
  dynamic fEFEcha;
  String? documentoNombre;
  String? documentoDireccion;
  String? documentoNit;
  dynamic observacionDocumento;
  dynamic observacion2;
  dynamic observacionGeneral;
  int? condicionesPago;
  String? documentoTelefono;
  String? documentoEMail;
  String? idCuenta;
  DateTime? fechaDocumento;
  DateTime? fechaHora;
  int? producto;
  String? productoId;
  String? unidadMedida;
  String? simbolo;
  String? desProducto;
  String? bodega;
  double? cantidad;
  double? cantidadPos;
  String? observacion1;
  String? montoUMTipoMoneda;
  String? montoTotalTipoMoneda;
  double? monto;
  double? montoMoneda;
  int? moneda;
  String? simboloMoneda;
  double? montoTotalUnitario;
  double? montoTotal;
  String? tipoCambio;
  String? tipoDocumentoPersonalizado;
  String? direccionSerie;
  String? telefonoSerie;
  String? atendio;
  dynamic transaporte;
  String? mensajeExento;
  dynamic oc;
  dynamic op;
  dynamic tipoFactura;
  dynamic leyenda;
  String? regimen;
  String? reimpresion;
  double? subTotal;
  double? descuento;

  PrintConvertModel({
    required this.montoLetras,
    required this.idDocumento,
    required this.refIdDocumento,
    required this.username,
    required this.razonSocial,
    required this.empresaNombre,
    required this.empresaDireccion,
    required this.empresaNit,
    required this.paginaWeb,
    required this.empresaCorreo,
    required this.empresaPbx,
    required this.empresaDireccionF,
    required this.empresaTelefono,
    required this.tipoDocumento,
    required this.serieDocumento,
    required this.serieResolucion,
    required this.serieFechaAutorizacion,
    required this.serieIni,
    required this.serieFin,
    required this.serieFormaPago,
    required this.sucursalTelefono,
    required this.sucursalDireccion,
    required this.sucursalNombre,
    required this.departamentoSerie,
    required this.municipioSerie,
    required this.fEIdDocumento,
    required this.fESerie,
    required this.fECae,
    required this.fEFEcha,
    required this.documentoNombre,
    required this.documentoDireccion,
    required this.documentoNit,
    required this.observacionDocumento,
    required this.observacion2,
    required this.observacionGeneral,
    required this.condicionesPago,
    required this.documentoTelefono,
    required this.documentoEMail,
    required this.idCuenta,
    required this.fechaDocumento,
    required this.fechaHora,
    required this.producto,
    required this.productoId,
    required this.unidadMedida,
    required this.simbolo,
    required this.desProducto,
    required this.bodega,
    required this.cantidad,
    required this.cantidadPos,
    required this.observacion1,
    required this.montoUMTipoMoneda,
    required this.montoTotalTipoMoneda,
    required this.monto,
    required this.montoMoneda,
    required this.moneda,
    required this.simboloMoneda,
    required this.montoTotalUnitario,
    required this.montoTotal,
    required this.tipoCambio,
    required this.tipoDocumentoPersonalizado,
    required this.direccionSerie,
    required this.telefonoSerie,
    required this.atendio,
    required this.transaporte,
    required this.mensajeExento,
    required this.oc,
    required this.op,
    required this.tipoFactura,
    required this.leyenda,
    required this.regimen,
    required this.reimpresion,
    required this.subTotal,
    required this.descuento,
  });

  factory PrintConvertModel.fromJson(String str) =>
      PrintConvertModel.fromMap(json.decode(str));

  String toJson() => json.encode(toMap());

  factory PrintConvertModel.fromMap(Map<String, dynamic> json) =>
      PrintConvertModel(
        montoLetras: json["monto_Letras"],
        idDocumento: json["id_Documento"],
        refIdDocumento: json["ref_Id_Documento"],
        username: json["username"],
        razonSocial: json["razon_Social"],
        empresaNombre: json["empresa_Nombre"],
        empresaDireccion: json["empresa_Direccion"],
        empresaNit: json["empresa_Nit"],
        paginaWeb: json["pagina_Web"],
        empresaCorreo: json["empresa_Correo"],
        empresaPbx: json["empresa_PBX"],
        empresaDireccionF: json["empresa_Direccion_F"],
        empresaTelefono: json["empresa_Telefono"],
        tipoDocumento: json["tipo_Documento"],
        serieDocumento: json["serie_Documento"],
        serieResolucion: json["serie_Resolucion"],
        serieFechaAutorizacion: json["serie_Fecha_Autorizacion"],
        serieIni: json["serie_Ini"],
        serieFin: json["serie_Fin"],
        serieFormaPago: json["serie_Forma_Pago"],
        sucursalTelefono: json["sucursal_Telefono"],
        sucursalDireccion: json["sucursal_Direccion"],
        sucursalNombre: json["sucursal_Nombre"],
        departamentoSerie: json["departamento_Serie"],
        municipioSerie: json["municipio_Serie"],
        fEIdDocumento: json["fE_Id_Documento"],
        fESerie: json["fE_Serie"],
        fECae: json["fE_CAE"],
        fEFEcha: json["fE_FEcha"],
        documentoNombre: json["documento_Nombre"],
        documentoDireccion: json["documento_Direccion"],
        documentoNit: json["documento_Nit"],
        observacionDocumento: json["observacion_Documento"],
        observacion2: json["observacion_2"],
        observacionGeneral: json["observacion_General"],
        condicionesPago: json["condiciones_Pago"],
        documentoTelefono: json["documento_Telefono"],
        documentoEMail: json["documento_EMail"],
        idCuenta: json["id_Cuenta"],
        fechaDocumento: DateTime.parse(json["fecha_Documento"]),
        fechaHora: DateTime.parse(json["fecha_Hora"]),
        producto: json["producto"],
        productoId: json["producto_Id"],
        unidadMedida: json["unidad_Medida"],
        simbolo: json["simbolo"],
        desProducto: json["des_Producto"],
        bodega: json["bodega"],
        cantidad: json["cantidad"],
        cantidadPos: json["cantidad_Pos"],
        observacion1: json["observacion_1"],
        montoUMTipoMoneda: json["monto_U_M_Tipo_Moneda"],
        montoTotalTipoMoneda: json["monto_Total_Tipo_Moneda"],
        monto: json["monto"],
        montoMoneda: json["monto_Moneda"]?.toDouble(),
        moneda: json["moneda"],
        simboloMoneda: json["simbolo_Moneda"],
        montoTotalUnitario: json["monto_Total_Unitario"],
        montoTotal: json["monto_Total"],
        tipoCambio: json["tipo_Cambio"],
        tipoDocumentoPersonalizado: json["tipo_Documento_Personalizado"],
        direccionSerie: json["direccion_Serie"],
        telefonoSerie: json["telefono_Serie"],
        atendio: json["atendio"],
        transaporte: json["transaporte"],
        mensajeExento: json["mensaje_Exento"],
        oc: json["oc"],
        op: json["op"],
        tipoFactura: json["tipo_Factura"],
        leyenda: json["leyenda"],
        regimen: json["regimen"],
        reimpresion: json["reimpresion"],
        subTotal: json["sub_Total"],
        descuento: json["descuento"],
      );

  Map<String, dynamic> toMap() => {
        "monto_Letras": montoLetras,
        "id_Documento": idDocumento,
        "ref_Id_Documento": refIdDocumento,
        "username": username,
        "razon_Social": razonSocial,
        "empresa_Nombre": empresaNombre,
        "empresa_Direccion": empresaDireccion,
        "empresa_Nit": empresaNit,
        "pagina_Web": paginaWeb,
        "empresa_Correo": empresaCorreo,
        "empresa_PBX": empresaPbx,
        "empresa_Direccion_F": empresaDireccionF,
        "empresa_Telefono": empresaTelefono,
        "tipo_Documento": tipoDocumento,
        "serie_Documento": serieDocumento,
        "serie_Resolucion": serieResolucion,
        "serie_Fecha_Autorizacion": serieFechaAutorizacion,
        "serie_Ini": serieIni,
        "serie_Fin": serieFin,
        "serie_Forma_Pago": serieFormaPago,
        "sucursal_Telefono": sucursalTelefono,
        "sucursal_Direccion": sucursalDireccion,
        "sucursal_Nombre": sucursalNombre,
        "departamento_Serie": departamentoSerie,
        "municipio_Serie": municipioSerie,
        "fE_Id_Documento": fEIdDocumento,
        "fE_Serie": fESerie,
        "fE_CAE": fECae,
        "fE_FEcha": fEFEcha,
        "documento_Nombre": documentoNombre,
        "documento_Direccion": documentoDireccion,
        "documento_Nit": documentoNit,
        "observacion_Documento": observacionDocumento,
        "observacion_2": observacion2,
        "observacion_General": observacionGeneral,
        "condiciones_Pago": condicionesPago,
        "documento_Telefono": documentoTelefono,
        "documento_EMail": documentoEMail,
        "id_Cuenta": idCuenta,
        "fecha_Documento": fechaDocumento!.toIso8601String(),
        "fecha_Hora": fechaHora!.toIso8601String(),
        "producto": producto,
        "producto_Id": productoId,
        "unidad_Medida": unidadMedida,
        "simbolo": simbolo,
        "des_Producto": desProducto,
        "bodega": bodega,
        "cantidad": cantidad,
        "cantidad_Pos": cantidadPos,
        "observacion_1": observacion1,
        "monto_U_M_Tipo_Moneda": montoUMTipoMoneda,
        "monto_Total_Tipo_Moneda": montoTotalTipoMoneda,
        "monto": monto,
        "monto_Moneda": montoMoneda,
        "moneda": moneda,
        "simbolo_Moneda": simboloMoneda,
        "monto_Total_Unitario": montoTotalUnitario,
        "monto_Total": montoTotal,
        "tipo_Cambio": tipoCambio,
        "tipo_Documento_Personalizado": tipoDocumentoPersonalizado,
        "direccion_Serie": direccionSerie,
        "telefono_Serie": telefonoSerie,
        "atendio": atendio,
        "transaporte": transaporte,
        "mensaje_Exento": mensajeExento,
        "oc": oc,
        "op": op,
        "tipo_Factura": tipoFactura,
        "leyenda": leyenda,
        "regimen": regimen,
        "reimpresion": reimpresion,
        "sub_Total": subTotal,
        "descuento": descuento,
      };
}
