import 'dart:convert';

class EncabezadoModel {
  String? idDocumento;
  String? empresaNombre;
  String? razonSocial;
  String? empresaDireccion;
  String? empresaNit;
  String? paginaWeb;
  String? empresaCorreo;
  String? empresaPbx;
  String? empresaDireccionF;
  String? empresaTelefono;
  String? tipoDocumento;
  String? serieDocumento;
  String? serieResolucion;
  String? serieFechaAutorizacion;
  String? serieIni;
  String? serieFin;
  String? serieFormaPago;
  String? serieObervacion;
  String? certificadorDteNombre;
  String? certificadorDteNit;
  String? iDDocumentoRef;
  String? feLNumeroDocumento;
  dynamic feLSerie;
  dynamic feLUuid;
  dynamic feLFechaCertificacion;
  String? montoLetras;
  int preview;
  dynamic impresora;
  dynamic copias;
  dynamic formato;
  dynamic refTipoReferencia;
  dynamic refFechaIni;
  dynamic refFechaFin;
  dynamic fechaIni;
  dynamic fechaFin;
  dynamic refObservacion2;
  dynamic refDescripcion;
  dynamic refObservacion3;
  dynamic refObservacion;
  dynamic fDesTipoReferencia;
  dynamic cuentaCorrentistaRefEMail;
  dynamic cantidadDiasFechaIniFin;
  String? observacion1;
  String? formaPagoIsr;
  String? ccFacturaNombre;
  String? ccFacturaNit;
  String? ccFacturaDireccion;
  String? ccTelefono;
  String? docFechaDocumento;
  String? ccEMail;
  String? cuentaCorrentistaRefNombre;
  String? userName;

  EncabezadoModel({
    required this.idDocumento,
    required this.empresaNombre,
    required this.razonSocial,
    required this.empresaDireccion,
    required this.empresaNit,
    required this.paginaWeb,
    required this.empresaCorreo,
    required this.empresaPbx,
    required this.empresaDireccionF,
    required this.empresaTelefono,
    required this.tipoDocumento,
    required this.serieDocumento,
    required this.serieResolucion,
    required this.serieFechaAutorizacion,
    required this.serieIni,
    required this.serieFin,
    required this.serieFormaPago,
    required this.serieObervacion,
    required this.certificadorDteNombre,
    required this.certificadorDteNit,
    required this.iDDocumentoRef,
    required this.feLNumeroDocumento,
    required this.feLSerie,
    required this.feLUuid,
    required this.feLFechaCertificacion,
    required this.montoLetras,
    required this.preview,
    required this.impresora,
    required this.copias,
    required this.formato,
    required this.refTipoReferencia,
    required this.refFechaIni,
    required this.refFechaFin,
    required this.fechaIni,
    required this.fechaFin,
    required this.refObservacion2,
    required this.refDescripcion,
    required this.refObservacion3,
    required this.refObservacion,
    required this.fDesTipoReferencia,
    required this.cuentaCorrentistaRefEMail,
    required this.cantidadDiasFechaIniFin,
    required this.observacion1,
    required this.formaPagoIsr,
    required this.ccFacturaNombre,
    required this.ccFacturaNit,
    required this.ccFacturaDireccion,
    required this.ccTelefono,
    required this.docFechaDocumento,
    required this.ccEMail,
    required this.cuentaCorrentistaRefNombre,
    required this.userName,
  });

  factory EncabezadoModel.fromJson(String str) =>
      EncabezadoModel.fromMap(json.decode(str));

  String toJson() => json.encode(toMap());

  factory EncabezadoModel.fromMap(Map<String, dynamic> json) => EncabezadoModel(
        idDocumento: json["id_Documento"],
        empresaNombre: json["empresa_Nombre"],
        razonSocial: json["razon_Social"],
        empresaDireccion: json["empresa_Direccion"],
        empresaNit: json["empresa_Nit"],
        paginaWeb: json["pagina_Web"],
        empresaCorreo: json["empresa_Correo"],
        empresaPbx: json["empresa_PBX"],
        empresaDireccionF: json["empresa_Direccion_F"],
        empresaTelefono: json["empresa_Telefono"],
        tipoDocumento: json["tipo_Documento"],
        serieDocumento: json["serie_Documento"],
        serieResolucion: json["serie_Resolucion"],
        serieFechaAutorizacion: json["serie_Fecha_Autorizacion"],
        serieIni: json["serie_Ini"],
        serieFin: json["serie_Fin"],
        serieFormaPago: json["serie_Forma_Pago"],
        serieObervacion: json["serie_Obervacion"],
        certificadorDteNombre: json["certificador_DTE_Nombre"],
        certificadorDteNit: json["certificador_DTE_NIT"],
        iDDocumentoRef: json["iD_Documento_Ref"],
        feLNumeroDocumento: json["feL_numeroDocumento"],
        feLSerie: json["feL_Serie"],
        feLUuid: json["feL_UUID"],
        feLFechaCertificacion: json["feL_fechaCertificacion"],
        montoLetras: json["monto_Letras"],
        preview: json["preview"],
        impresora: json["impresora"],
        copias: json["copias"],
        formato: json["formato"],
        refTipoReferencia: json["ref_Tipo_Referencia"],
        refFechaIni: json["ref_Fecha_Ini"],
        refFechaFin: json["ref_Fecha_Fin"],
        fechaIni: json["fecha_Ini"],
        fechaFin: json["fecha_Fin"],
        refObservacion2: json["ref_Observacion_2"],
        refDescripcion: json["ref_Descripcion"],
        refObservacion3: json["ref_Observacion_3"],
        refObservacion: json["ref_Observacion"],
        fDesTipoReferencia: json["fDes_Tipo_Referencia"],
        cuentaCorrentistaRefEMail: json["cuenta_Correntista_Ref_EMail"],
        cantidadDiasFechaIniFin: json["cantidad_Dias_Fecha_Ini_Fin"],
        observacion1: json["observacion_1"],
        formaPagoIsr: json["forma_Pago_ISR"],
        ccFacturaNombre: json["cC_Factura_Nombre"],
        ccFacturaNit: json["cC_Factura_NIT"],
        ccFacturaDireccion: json["cC_Factura_Direccion"],
        ccTelefono: json["cC_Telefono"],
        docFechaDocumento: json["doc_Fecha_Documento"],
        ccEMail: json["cC_EMail"],
        cuentaCorrentistaRefNombre: json["cuenta_Correntista_Ref_Nombre"],
        userName: json["userName"],
      );

  Map<String, dynamic> toMap() => {
        "id_Documento": idDocumento,
        "empresa_Nombre": empresaNombre,
        "razon_Social": razonSocial,
        "empresa_Direccion": empresaDireccion,
        "empresa_Nit": empresaNit,
        "pagina_Web": paginaWeb,
        "empresa_Correo": empresaCorreo,
        "empresa_PBX": empresaPbx,
        "empresa_Direccion_F": empresaDireccionF,
        "empresa_Telefono": empresaTelefono,
        "tipo_Documento": tipoDocumento,
        "serie_Documento": serieDocumento,
        "serie_Resolucion": serieResolucion,
        "serie_Fecha_Autorizacion": serieFechaAutorizacion,
        "serie_Ini": serieIni,
        "serie_Fin": serieFin,
        "serie_Forma_Pago": serieFormaPago,
        "serie_Obervacion": serieObervacion,
        "certificador_DTE_Nombre": certificadorDteNombre,
        "certificador_DTE_NIT": certificadorDteNit,
        "iD_Documento_Ref": iDDocumentoRef,
        "feL_numeroDocumento": feLNumeroDocumento,
        "feL_Serie": feLSerie,
        "feL_UUID": feLUuid,
        "feL_fechaCertificacion": feLFechaCertificacion,
        "monto_Letras": montoLetras,
        "preview": preview,
        "impresora": impresora,
        "copias": copias,
        "formato": formato,
        "ref_Tipo_Referencia": refTipoReferencia,
        "ref_Fecha_Ini": refFechaIni,
        "ref_Fecha_Fin": refFechaFin,
        "fecha_Ini": fechaIni,
        "fecha_Fin": fechaFin,
        "ref_Observacion_2": refObservacion2,
        "ref_Descripcion": refDescripcion,
        "ref_Observacion_3": refObservacion3,
        "ref_Observacion": refObservacion,
        "fDes_Tipo_Referencia": fDesTipoReferencia,
        "cuenta_Correntista_Ref_EMail": cuentaCorrentistaRefEMail,
        "cantidad_Dias_Fecha_Ini_Fin": cantidadDiasFechaIniFin,
        "observacion_1": observacion1,
        "forma_Pago_ISR": formaPagoIsr,
        "cC_Factura_Nombre": ccFacturaNombre,
        "cC_Factura_NIT": ccFacturaNit,
        "cC_Factura_Direccion": ccFacturaDireccion,
        "cC_Telefono": ccTelefono,
        "doc_Fecha_Documento": docFechaDocumento,
        "cC_EMail": ccEMail,
        "cuenta_Correntista_Ref_Nombre": cuentaCorrentistaRefNombre,
        "userName": userName,
      };
}
